[package]
name = "mullvad-daemon"
version = "2020.6.0-beta1"
authors = ["Mullvad VPN"]
description = "Mullvad VPN daemon. Runs and controls the VPN tunnels"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
cfg-if = "0.1"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.25"
err-derive = "0.2.1"
fern = { version = "0.5", features = ["colored"] }
futures01 = { package = "futures", version = "0.1" }
futures = { package = "futures", version = "0.3", features = [ "compat" ]}
ipnetwork = "0.16"
lazy_static = "1.0"
log = "0.4"
log-panics = "2.0.0"
parking_lot = "0.9"
rand = "0.7"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features =  [ "io-util", "process", "rt-core", "rt-threaded", "stream", "fs"] }
uuid = { version = "0.7", features = ["v4"] }

mullvad-paths = { path = "../mullvad-paths" }
mullvad-types = { path = "../mullvad-types" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }

mullvad-management-interface = { path = "../mullvad-management-interface" }
triggered = "0.1.1"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
nix = "0.17"
simple-signal = "1.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.0"
duct = "0.13"
windows-service = "0.3"
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "libloaderapi", "ntlsa", "synchapi", "tlhelp32", "winbase", "winerror", "winuser"] }
dirs = "2.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2020 Mullvad VPN AB"
InternalName = "mullvad-daemon"
OriginalFilename = "mullvad-daemon.exe"
